# -*- coding: utf-8 -*-
"""
Created on Fri May 18 20:50:17 2018

@author: anandrathi
"""

def getAntiHeaders():
    ANTI_HEADER= [
        "Programmer Analyst",
        ]
    return ANTI_HEADER

def getMainHeaders():
  MAINHEADERS = [
  "Technical & Analytical skill-set",        
  "skype"
  "E-mail",
  "E-mail   id",
  "it exposure",
  "technologies hired",
  "projects perfected",
  "tools & softwares",
  "objective",
  "educational record",
  "experience chronology",
  "academic  profile",
  "training assignments",
  "personal description",
  "education / professional development",
  "education & academics",
  "internship training",
  "languages & databases",
  "experience  summery",
  "technologies used",
  "summary (project)",
  "training of end",
  "professional skill",
  "training & projects undertaken",
  "training completion",
  "references on request",
  "interests / hobbies",
  "academic qualificati",
  "training company",
  "technologies ltd",
  "experience details",
  "education and certifications",
  "key academic projects",
  "education qualification",
  "profile summary",
  "place of residence",
  "personal minutiae",
  "experience  summary",
  "personal infomation",
  "experience   details",
  "professional certification",
  "professional course",
  "personal blogging",
  "summary of skill",
  "total work experience",
  "skills & expertise",
  "passport systems",
  "skills / abilities",
  "skills in various",
  "technologies skills",
  "area of interests",
  "academic acheivement",
  "skills and knowledge acquired through experience & training",
  "project undertaken",
  "project details",
  "education",
  "extra-curricular activity",
  "personal achievements",
  "personal details",
  "synopsis",
  "co-curricular",
  "internship experience",
  "profile management",
  "extra  curricullar  activities",
  "experience in",
  "expertise in a wide",
  "academic experience",
  "awards & achivements",
  "objective of project",
  "projects and seminars",
  "professional summery",
  "educational synopsis",
  "tools used",
  "passport no k6346115",
  "professional overview",
  "affiliations",
  "passport",
  "academic qualification",
  "language ",
  "job profile summary",
  "hobbies &interest",
  "training new joiners",
  "organization syntel",
  "strengths",
  "hobbies/interests",
  "career recital",
  "educational summary",
  "academic highlights",
  "project worked on",
  "training program name",
  "projects concurrently",
  "experience  history",
  "achievement at",
  "passport	validity",
  "activity monitor",
  "personal traits",
  "roles and responsibility",
  "achivements",
  "activity template",
  "awards and rewards",
  "hobby",
  "software projects",
  "technical qualification",
  "areas of interest",
  "areas of expertise",
  "dates organization",
  "academic achievements",
  "personal overview",
  "languages & markups",
  "experience in",
  "address for communication",
  "projects & poc",
  "awards & accolades",
  "professional matrix",
  "date of birth& age",
  "hobbies & interest",
  "languages",
  "technologies indore",
  "technologies  used",
  "interests / strength",
  "academic  credentials",
  "professional projects",
  "summertraining",
  "aim of the project",
  "projects involved in",
  "experience in months",
  "experiences",
  "academic achievemnets",
  "professional image",
  "strengths / skills",
  "tools/technologies",
  "projects undertaking",
  "tools and framework",
  "certifications/licenses",
  "career contour",
  "contact no",
  "certified courses",
  "academic summary",
  "project executed",
  "professional  summary",
  "projects for 2 years",
  "experience with mvc",
  "skill sets",
  "professional préface",
  "dated 18th feb",
  "contact 09884646668",
  "industrial training",
  "professional goals",
  "summer training project",
  "training programme",
  "skillsets",
  "projects timelines",
  "educational qualification",
  "language",
  "projects worked on",
  "projects struture",
  "tools  knowledge",
  "projects and poc",
  "strengths and hobbies",
  "organization for the",
  "hobbies &activites",
  "secondary skillset",
  "experiences",
  "objective statement",
  "assertion",
  "academic",
  "experience history",
  "projects/internships",
  "synopsis professional",
  "declarations",
  "project details ",
  "projects experience",
  "certification no",
  "work history",
  "projects history",
  "projects to mention",
  "hobbies and leisure",
  "training details",
  "work experince",
  "personalizing his",
  "proficient in",
  "training/certificate",
  "training  experience",
  "experience narrative",
  "project executed",
  "top skills",
  "organization",
  "language cognizance",
  "academicaccolades",
  "publications/presentations",
  "skills & software",
  "awards / accolades",
  "experience domain",
  "tools & software",
  "projects working on",
  "training	attended",
  "tools used in project",
  "other skills",
  "projects spanning",
  "profile   summary",
  "projects under taken",
  "projects handling",
  "academic counselor",
  "course and certification",
  "skills/specialities",
  "organizational skills",
  "career progression",
  "language/methodology",
  "educational  profile",
  "key strenghts",
  "career synopsis",
  "language/technology",
  "tools/environments",
  "tools & techniques",
  "certificates & training",
  "experience",
  "work experience",
  "personality   traits",
  "key skills in vmware",
  "position overview",
  "curriculum vitae",
  "educational detail",
  "projects health care",
  "personal synopsis",
  "email",
  "projects and changes",
  "trainings  underwent",
  "contact no",
  "educationdetails",
  "academic   profile",
  "working experience",
  "projects information",
  "academic year",
  "significant highlight",
  "professional profile",
  "technical training and certification",
  "academic associate",
  "experience in it",
  "training sessions",
  "personal  details",
  "awards and accolades",
  "projects (worked on)",
  "profile   summary",
  "excellence",
  "projects abstracts",
  "key skill sets",
  "achievement",
  "strengths & skills",
  "core competencies",
  "academic performance",
  "organization growth",
  "academic research",
  "tools and approaches",
  "curriculum vitaé",
  "objectives were met",
  "project details",
  "technologies stack",
  "hobby and interest",
  "skill set trained on",
  "highlights",
  "dates of employment",
  "skills and strength",
  "contact no",
  "education  details",
  "technical education",
  "it experience",
  "skills used",
  "acadamic profile",
  "seminars and presentations",
  "project work details",
  "project work",
  "personal   profile",
  "education history",
  "technical skillsets",
  "skills and strengths",
  "hallmark",
  "educationalâ qualification",
  "project profile",
  "organization/location",
  "tools/frameworks used",
  "summary of resume",
  "project and work responsibilities",
  "passport js",
  "languages core java",
  "technical skills set",
  "knowledge & skills",
  "trainings delivered",
  "training & project",
#  "date",
  "language & tools",
  "qualification level",
  "objective profile",
  "career skills / knowledge",
  "skills and abilities",
  "personal detaiflse",
  "experience recital",
  "projects/ websites",
  "languages proficiency",
  "professional summary",
  "curriculum details",
  "project summary",
  "job experience",
  "educational dossier",
  "professional trainings",
  "computer certification",
  "internship  program",
  "projects overview",
  "contacts & vendors",
  "courses / certificate",
  "experience 9 years",
  "training& certifications",
  "accolades",
  "email and telephone",
  "career achievements",
  "languages",
  "personaldetails",
  "professional training",
  "current job responsibilities",
  "experience overview",
  "projects experiences",
  "employers details",
  "projects/ products",
  "projects profile",
  "qualification/degree",
  "language pl/sql",
  "tools & packages",
  "personal detail’s",
  "tools & frameworks",
  "training location",
  "languages and tools",
  "educational records",
  "contact information",
  "professional summary",
  "academic details",
  "trainings achieved",
  "education & learning",
  "technical proficiencies",
  "training/courses",
  "professionalsummary",
  "qualification",
  "training description",
  "professional services",
  "education background",
  "co-curriculars",
  "training projects",
  "roles and responsibilities",
  "date of birth",
  "professional contour",
  "academic achievement",
  "awards & credentials",
  "projects using maven",
  "professional digest",
  "organizational goals",
  "hobbies/activity",
  "project details",
  "date of relinquish",
  "achievements & extra curricular activities",
  "present address",
  "hobbies",
  "training & support",
  "projects done here",
  "experience highlights",
  "educational credentals",
  "professional networks",
  "interests & hobbies",
  "projectsandtrainings",
  "educations & courses",
  "executive synopsis",
  "skills & competences",
  "functional skills set",
  "date   of   birth",
  "qualifications year",
  "experienced summary",
  "academic	background",
  "languages & database",
  "tools			eclipse sde",
  "reward & recognition",
  "training/certification details",
  "brief description",
  "scholastics",
  "education & degrees",
  "project details",
  "educational status",
  "key technical skills",
  "passport availability",
  "experience 2 years",
  "languages  known",
  "profile and objective",
  "skills and knowledge acquired through education and experience",
  "personal strengths",
  "profile snapshot",
  "certification done",
  "academia projects",
  "education   details",
  "projects   wikonnect",
  "tools behave bdd",
  "projects at glance",
  "professional preface",
  "areas of interests",
  "trainings",
  "hobbies &activities",
  "awards and recognitions",
  "academics trainings",
  "extracurricular activities",
  "key responsibilities handled",
  "qualification/course",
  "skills & trainings",
  "technical skill",
  "software skills",
  "responsibilities held",
  "certification summary",
  "interests &hobbies",
  "work experience’s",
  "projects/clients",
  "achivements & awards",
  "working experience in",
  "carrir objective",
  "qualifications",
  "academic snapshot",
  "experience in ",
  "co-curricular activities",
  "award & achievements",
  "professional website",
  "profile  description",
  "training / courses",
  "experience in domain",
  "personal strength",
  "personal info",
  "tools worked on",
  "languages pl/sql",
  "projects on qlikview",
  "personal objective",
  "passport/visa details",
  "educational qualifications",
  "additional information",
  "professional	history",
  "academic excellence",
  "education credential",
  "languages/frameworks",
  "employee experience",
  "project executed",
  "organisational experience",
  "contact centre suite",
  "education/scholastics",
  "experience snapshot",
  "summary experience",
  "summer internships",
  "reporting skills",
  "strength and skills",
  "rewards and accolades",
  "training and project",
  "tools /db/packages",
  "tools and ides used",
  "personal profile",
  "personal background",
  "awards & achievements",
  "personal dossier",
  "career interests",
  "interpersonal skills",
  "awards for excellence",
  "project profile",
  "technical experience and proficiency",
  "organization’s name",
  "co-curricular activities/ achievements",
  "expertise include",
  "technologies used",
  "academic profile",
  "experience ",
  "curriculum vittae",
  "professional",
  "skills matrix tracker",
  "document types and other deliverables",
  "email",
  "tools/ technologies",
  "personal    profile",
  "professional certifications",
  "training/project work",
  "personal competence",
  "passport expiry date",
  "experienced in",
  "curriculum",
  "educational institute",
  "academic trainings",
  "achievements & accomplishments",
  "qualifications/certifications",
  "professional skills",
  "languages/utilities",
  "email id (personal)",
  "personalqualities",
  "language/platform",
  "knowledge purview",
  "professional forte",
  "tools & practices",
  "training programmes",
  "network voip skills",
  "academics profile",
  "onsite experience",
  "academic records",
  "academics details",
  "profile & experience summary",
  "synopsis / summary",
  "personal sysnopsis",
  "achievements",
  "academic accolade",
  "awards & achivement",
  "academics credentials",
  "build release executive",
  "skill summary",
  "computer skills",
  "summer training",
  "summary of  sd skills",
  "organizational goal",
  "projects as well",
  "key skills",
  "professional details",
  "professional liaison",
  "tools worked with",
  "project profile 1",
  "leadership skills",
  "training and certification",
  "objective and skill /",
  "academic & professional achievements",
  "education qualifications",
  "expertise in team",
  "skills focusing roi",
  "organizational growth",
  "professional expericence and achievements",
  "strengths weaknesses",
  "activity management",
  "organization’s growth",
  "job profile in brief",
  "academic career",
  "education scoring",
  "experience record",
  "accomplishments",
  "tools & technologies",
  "career milestones",
  "awards/recognition",
  "educational & professional credentials",
  "personal biography",
  "agile project experience",
  "tools and information",
  "projects walkthrough",
  "final year projects",
  "passport",
  "awards/ achievement",
  "hardware skills",
  "other certification",
  "educational development",
  "career objective0",
  "training attended",
  "educational details",
  "experiencedetails",
  "projects detail",
  "personal detailes",
  "executive profile",
  "hoobies and activities",
  "work & experiance",
  "professional status",
  "projects explosure",
  "key projects executed",
  "intrest $ hobbies",
  "personal information",
  "academic credentials",
  "language/database",
  "personal abilities",
  "professional experience",
  "software skills set",
  "interests include",
  "professional brief",
  "education) training",
  "projects worked upon",
  "professional work experience",
  "skillset overview",
  "awards & extra curricular activities",
  "secondary skills",
  "organisational scan",
  "experience in",
  "project profile ",
  "personal attributes",
  "excellence",
  "experience learning",
  "skills and tools",
  "awards / recognition",
  "organization details",
  "skill set",
  "organization/company",
  "academic overview",
  "academic knowledge",
  "career snapshot",
  "contact centre skills",
  "skills & knowledge",
  "professional awards",
  "computer proficiency",
  "languages & platforms",
  "profile highlights",
  "projects snapshot",
  "professional sumary",
  "trainings & learning",
  "trainings imparted",
  "technologies pvt ltd)",
  "experience skills",
  "educational credentials",
  "training & projects",
  "experience detail",
  "language emulator",
  "project details (9)",
  "strengths & abilities",
  "projects highlights",
  "training to new user",
  "academic chronicle",
  "awards & training",
  "objectives",
  "skills & activities",
  "computer  proficiency",
  "academic activities",
  "knowledge base/technical skills",
  "experience",
  "professional organizations",
  "date & time prompt",
  "training highlights",
  "personal snapshot",
  "professional qualifications",
  "objective objective",
  "responsibilitiese",
  "certification testing",
  "hobbies and interests",
  "profile attributes",
  "languages/technology",
  "date",
  "certification of java",
  "experience on linux",
  "experience summery",
  "additional qualification and profesional certication",
  "awards /recognitions",
  "projects  undertaken",
  "training undertaken",
  "awards/ achievements",
  "training and projects",
  "skills and hobbies",
  "awards &achievements",
  "experience (in years)",
  "contactno",
  "experience gained",
  "technical compentencies",
  "personal weakness",
  "summary & experience",
  "total experience",
  "currently working",
  "srengths",
  "achievement at ",
  "tools and utilities",
  "educational skills",
  "awards& achievements",
  "experience on",
  "carrier summary",
  "strenghts",
  "training conducted",
  "academic project",
  "database skills",
  "awards	&	achievements",
  "achievements/awards",
  "languages & scripting",
  "online ranksheet certification",
  "career history",
  "organization success",
  "work experience",
  "project profile’s",
  "projects & trainings",
  "professional outline",
  "skills and strenghts",
  "training courses",
  "training purpose",
  "personal e",
  "academics summary",
  "employment chronicle",
  "area of intrest",
  "tools known to work",
  "work experience",
  "professional	profile",
  "professional career",
  "experience in brief",
  "professional profile",
  "professional précis",
  "personal  profile",
  "professional track",
  "organization summary",
  "achievements/tasks",
  "sql data base skills",
  "project details",
  "educational detailes",
  "date and effective",
  "work experience",
  "projects websites",
  "personal   details",
  "project details",
  "education highlights",
  "educational background",
  "experience includes",
  "strength & profile",
  "educational projects",
  "expertise in",
  "personal skills",
  "technical expertise",
  "education experience",
  "academics background",
  "training team mates",
  "technical summary",
  "job profile handled",
  "academic history",
  "experience profile",
  "hobbies & passions",
  "skills & technologies",
  "qualifications summary",
  "achivements & extra curricular activity",
  "tools and tableau",
  "projects accomplished",
  "professional experience & details",
  "additional professional skills",
  "skills and keywords",
  "skills acquaintance",
  "technical skills and knowledge",
  "technical skill areas",
  "tools & environments",
  "extra- curricular activity & achievements",
  "projects handeled",
  "programmer analyst",
  "competency forte",
  "professional synopsis",
  "skill set highlights",
  "other informations",
  "profile	snapshot",
  "achievements / awards",
  "professional and academic qualification",
  "strengths and skills",
  "personal informetion",
  "organization  client",
  "profile and strength",
  "personal strenghts",
  "languages   known",
  "personality	dimen",
  "hobbies and interesrs",
  "experience",
  "key skills/strengths",
  "personal profiles",
  "training	undergone",
  "project summary",
  "training completed",
  "managing clients",
  "technology interest and research",
  "skillset",
  "seeking assignments",
  "technical skill sets",
  "skills & attributes",
  "synoposis",
  "profile summery",
  "project' done",
  "personal attribute",
  "training category",
  "current status (since january 2015)",
  "excellence in",
  "responsibilities as",
  "place of birth",
  "personal and profile",
  "hobbies& strength",
  "awards & acclaims",
  "passport",
  "projects worked",
  "other qualifications",
  "certification / board",
  "curriculum    vitae",
  "projects description",
  "training needs of",
  "achievement & award",
  "professional courses",
  "tools and softwares",
  "technical competencies",
  "personal detials",
  "projectsundertaken",
  "personal	details",
  "key projects handled",
  "projects managing",
  "skills",
  "personal qualities",
  "projects management",
  "employment history",
  "strength & weakness",
  "skills & strength",
  "education detail",
  "training  / courses",
  "working experiences",
  "career vision",
  "professional carrier",
  "internships/trainings",
  "projects",
  "skills & strengths",
  "achievement/hobbies",
  "personal projects",
  "overall experience",
  "passport information",
  "projects coordinated",
  "awards & certificate",
  "education /training",
  "technical experience",
  "experience   synopsis",
  "contact",
  "technologies quickly",
  "academic	education",
  "tools &technologies",
  "trainings	undertaken",
  "profession objective",
  "skills & proficiencies",
  "tools & methodologies",
  "experience in",
  "projects   summary",
  "place of issue",
  "personal email id",
  "personale dossier",
  "personal   profile",
  "career summary",
  "carrier objective",
  "tools",
  "objective c",
  "qualification details",
  "strengths & weakness",
  "summary",
  "awards/achievements",
  "personal  details",
  "past work history &  experience",
  "projects at",
  "strengths & interests",
  "profile to folders",
  "education foundation",
  "academic education",
  "internship project",
  "ex-curricular activities",
  "project experience",
  "skills and competency",
  "personal informations",
  "personal specifics",
  "projects & isas done",
  "education qulification",
  "curriculum projects",
  "languages/web/tools",
  "projects (college)",
  "projects undergone",
  "hobbies/ interests",
  "extra-curricular activities",
  "key projects summary",
  "project executed(2)",
  "skills and expertise",
  "tools and software",
  "professional experiance",
  "certification url",
  "other notable qualifications",
  "experience in years",
  "experience duration",
  "experience spanning",
  "tools proficiency",
  "skills & softwares",
  "training and seminars",
  "skills and interests",
  "educationalqualification",
  "activity logging",
  "certification/s",
  "awards and honour",
  "curriculum  vitae",
  "activity",
  "qualification(s)",
  "language(s)",
  "skills & technique",
  "languages known",
  "language/utilities",
  "interest & hobbies",
  "projects worked with",
  "projects and planning",
  "training  report",
  "technologies",
  "place for autopars",
  "education services",
  "academic projects",
  "awards and honors",
  "key projects undertaken",
  "professional carrer",
  "training employees",
  "training & education",
  "certification courses",
  "education / degrees",
  "awards&achievements",
  "tableau developer with accenture",
  "profile overview",
  "experience (concise)",
  "passport number",
  "trainings & workshops",
  "project details 3",
  "career objectives",
  "project profile 3",
  "academicals project",
  "synopsis of projects",
  "educatioanal qualification",
  "projects   experience",
  "educational sector",
  "projects assignments",
  "educational history",
  "extra curricular activties",
  "experience/expertise",
  "summer internship",
  "published titles",
  "qualification profile",
  "project details",
  "tools like cognos bi",
  "career overview",
  "overall professional experience",
  "project detail",
  "tools and packages",
  "projects within",
  "career scan",
  "trainings & achievements",
  "internships",
  "bss/ran engineer",
  "experience in detail",
  "contact address",
  "professional qualification",
  "currently working at",
  "experience showcase",
  "certificationtraining",
  "profile at a glance",
  "memberships",
  "academic curriculum",
  "hobbies	and	interests",
  "profile  summary",
  "key achievement",
  "programming skills",
  "professional strengths",
  "project experience highlights",
  "education scholastics",
  "professional timeline",
  "information technlogy skills",
  "previous experiences",
  "achievements &awards",
  "certification & education",
  "personal   skills",
  "curriculum vitate",
  "certifications held",
  "personal snippets",
  "working experience with",
  "it experience summary",
  "languages/database",
  "academic awards",
  "personal interests",
  "strength",
  "passport",
  "other information",
  "experience with av",
  "achievements if any",
  "achievements/extra-curricular",
  "professional   skills",
  "internship & projects",
  "personal paresis",
  "email automatically",
  "awards and achievements",
  "academic	projects",
  "personal portfolio",
  "awards & recognitions",
  "technical qualifications",
  "organization skills",
  "area of interest",
  "academics project",
  "training / internship",
  "placement module",
  "training & education",
  "personal skill set",
  "academical projects",
  "training/internship",
  "project details",
  "projects details",
  "training experience",
  "educational profile",
  "technical certification",
  "projects supported",
  "permanent address",
  "curriculum vitae`",
  "employer and role details",
  "industrial trainings",
  "responsibilities /",
  "educational strength",
  "research papers",
  "trainings / seminars",
  "strengths summary",
  "educational level",
  "declaration",
  "activity diagrams",
  "aim",
  "language  proficuency",
  "experience in",
  "certification details",
  "target job",
  "tools/ build tools",
  "languages   known",
  "professional summar",
  "personality trait",
  "accompolishments and accolades",
  "training and workshop",
  "skills / strengths",
  "participation and achievements",
  "strenths",
  "tools  & protocols",
  "professional summury",
  "hobbies / interests",
  "academic year  degree",
  "organization  session",
  "training & workshops",
  "contact details",
  "projects/internship",
  "work experience 2",
  "responsibilities as a",
  "summary of skills",
  "personal inormation",
  "academic accolades",
  "trainings conducted",
  "objective summary",
  "awards/certifications",
  "language used",
  "projects deal by me",
  "languages & gui tools",
  "education chronicle",
  "personal infromation",
  "internship projects",
  "work experience & professional experience",
  "interests/hobbies",
  "interests",
  "awards",
  "work profile summary",
  "projects and training",
  "responsibilities/",
  "academic pro",
  "current employers",
  "personnal details",
  "languages proficient",
  "project details",
  "organization etc",
  "professional history",
  "handled projects",
  "awards / achievements",
  "training services",
  "onsite exposure",
  "internship undertaken",
  "jobs profile",
  "proffesional qualification",
  "personal attribites",
  "internships attended",
  "activity performed",
  "certifications done",
  "projects involved",
  "hobbies & strengths",
  "organization and eii",
  "project profiles",
  "tools and languages",
  "curriculum   vitae",
  "technical proficencies",
  "languages",
  "internship chronicle",
  "professional exposure",
  "profile synopsis",
  "research experience",
  "professionalprofile",
  "awards for the events",
  "personalattributes",
  "personal porfile",
  "expertise in",
  "language depending on",
  "academics",
  "projects accomplished",
  "technologies/tools",
  "excellence sphere",
  "functional skills",
  "skills & abilities",
  "technical education)",
  "projects at",
  "current projects",
  "date of graduation",
  "extra-curricularactivities",
  "responsibilities and extra-curricular activities",
  "personal vitae",
  "project work status",
  "strength & hobbies",
  "technologies changes",
  "skills & abilitie",
  "date(s) attended",
  "summary of goals",
  "tools and software’s",
  "projects/applications",
  "projects underway",
  "employers summary",
  "technologies limited",
  "technology toolsets",
  "achievements/ awards",
  "personal  attitude",
  "technical skillset",
  "language",
  "contact  information",
  "expertise in",
  "organizational levels",
  "education credentials",
  "academic credential",
  "professional attainments",
  "language known",
  "internship on php",
  "experiencesummary",
  "profile information",
  "professional project",
  "activity reports",
  "linkedin profile",
  "languages worked on",
  "skills/knowledge",
  "skills set",
  "experience on verint",
  "awards and citations",
  "projects completed",
  "organization profile",
  "strength & skills",
  "placement scenario",
  "contact i nformation",
  "professional snapshot",
  "projects/products",
  "personal synopsys",
  "projects managed",
  "education and qualification",
  "trainings completed",
  "training undergone",
  "personal interest",
  "experience in",
  "personal profile",
  "professional projects",
  "organization’s needs",
  "awards and honours",
  "academic  details",
  "executive summary",
  "personal deetails",
  "training& activities",
  "technical proficiency",
  "current employer",
  "academic	credentials",
  "career abstract",
  "professional needs",
  "experience synopsis",
  "training to freshers",
  "key skills in",
  "projects/seminars",
  "personal  information",
  "personal assesment",
  "educationeducation",
  "skill/strenth",
  "skills profile",
  "professional summany",
  "educational chronicle",
  "personal experience",
  "training profile",
  "military service",
  "skills & strenghts",
  "awards",
  "educational project",
  "professionalskills",
  "experience",
  "trainings undergone",
  "synopsis projects",
  "key skills assessment",
  "personal integrity",
  "summary of experience",
  "hobbies &interests",
  "personal credentials",
  "skill set & strengths",
  "professional abstract",
  "profile in brief",
  "self-confidence",
  "tools documentation",
  "trainings received",
  "hobbies and intrest",
  "profile description",
  "projects undrtaken",
  "training activities",
  "project details (3)",
  "professional level",
  "certification(biba)",
  "experienceincludes",
  "proffesional experience",
  "organization period",
  "technologies like",
  "career profile",
  "[.*] project experience",
  "projects implemented",
  "experience  (months)",
  "personals details",
  "technical cognizance",
  "certification in",
  "achievements at work",
  "technical skills used",
  "curriculum|vitae",
  "tools & utilities",
  "responsibilities",
  "career objective & summary",
  "projects summary",
  "language and tools",
  "other skills set",
  "personal statement",
  "trainings attended",
  "personel information",
  "awards & recognition",
  "highlights of career",
  "work experiences",
  "passport no",
  "scholastic credentials",
  "email/chat process",
  "academic credentials / certifications / skills",
  "languages/scripting",
  "technical profile",
  "skills & specialties",
  "training received",
  "experience summary",
  "academic projects",
  "educationalsummary",
  "employment experience",
  "academics & others",
  "reward & recognitions",
  "education/training",
  "profile snap shot",
  "co-curricularactivities",
  "contact details",
  "business domain knowledge",
  "profile expossure",
  "key skills and competencies",
  "languages sql",
  "professional skills",
  "decleration",
  "interests & hobbies",
  "organization’s goal",
  "hobbies/ interest",
  "education qualifications workshops  trainings undertaken",
  "contact inforamtion",
  "education detals",
  "projects underwent",
  "projects exposure",
  "currently working in",
  "skills summary",
  "professional qual",
  "projects executed",
  "training  received",
  "training of trainer",
  "education haryana )",
  "job profile / role",
  "personal information",
  "certifications",
  "trainings & awards",
  "certifications url’s",
  "professional exp",
  "academicqualification",
  "tools and technology",
  "personal feature",
  "skill set summary",
  "projects to the team",
  "language & software",
  "email   id",
  "area of experties",
  "projects developed",
  "profile abstract",
  "technical  skills",
  "interests/activities",
  "skills & experience",
  "tools acquaintance",
  "computer knowledge",
  "academic qulifaction",
  "training & internship",
  "profile’ with the new",
  "training  attended",
  "training plans for",
  "projects/websites",
  "achievements/others",
  "education  degree",
  "profiles to the user",
  "profile snapshots",
  "education information",
  "curriculam vitae",
  "education & training",
  "it skills summary",
  "professional credentials",
  "job profile",
  "final year project",
  "personal strenght",
  "email          id",
  "project profile",
  "professional strength",
  "personality skills",
  "email/sms module",
  "strength and hobbies",
  "key projects managed",
  "certification",
  "certification course",
  "academic projetcs",
  "academic qualifcation",
  "employment details",
  "key strengths",
  "project management skills",
  "organization joined",
  "brief overview",
  "key strengths areas",
  "certification skills",
  "key project handled",
  "projects in company",
  "qualification year",
  "organization  details",
  "activity to start",
  "curriculums",
  "place",
  "it skill set",
  "summary of profession",
  "projects involvement",
  "training program",
  "professionally summary",
  "language knowledge",
  "academic training",
  "project experience",
  "experiences summery",
  "skills",
  "summary information",
  "career graph",
  "significant accomplishments",
  "technology platforms",
  "training & workshop",
  "passport status",
  "present address",
  "projects and seminar",
  "academics / trainings",
  "professional synopsys",
  "professional span",
  "currently working on",
  "profile",
  "career highlights",
  "projects chronolgy",
  "education  detail",
  "projects under envoy",
  "summary of strength",
  "organization name",
  "language",
  "internship and ipt",
  "career commencement and progression",
  "internshipdetails",
  "personal glipse",
  "interests and skills",
  "academic background",
  "certification/courses",
  "tools & technology",
  "education & awards",
  "certification date",
  "internship",
  "training programs",
  "organization and team",
  "academic information",
  "project experience",
  "awards  and  honour",
  "soft skills training",
  "trainings / courses",
  "academic project work",
  "training and courses",
  "job responsibilities",
  "technical skill’s",
  "extra curricular activities",
  "work experience",
  "academicminiprojects",
  "tecnical skills",
  "hobbies&interests",
  "transferrable skills",
  "education / academics",
  "experience (5",
  "project executed(1)",
  "awards and accomplishments",
  "organization(ngo)",
  "strengths & hobbies",
  "technologies myself",
  "employer details",
  "organization & self",
  "experience detailed",
  "personal particular",
  "date pratik soitkar",
  "training exposure",
  "projects",
  "passport details",
  "preceeding assignments",
  "experience chronicle",
  "internship details",
  "education details",
  "personal objectives",
  "tools aginity",
  "computer skill set",
  "profile includes",
  "career glipse",
  "key strength",
  "awards/appreciations",
  "certification code",
  "education profiles",
  "work experience with",
  "roles & responsibilities",
  "projects undertaken",
  "technical knowledge",
  "skills and knowledge",
  "certification process",
  "technical skills",
  "organizational scan",
  "training solutions",
  "references",
  "responsibilities in roles",
  "academic project done",
  "projects  profile",
  "hobbies / interest",
  "interests and hobbies",
  "strength and ability",
  "training on wordpress",
  "personal computer",
  "tools",
  "overview of spinning",
  "excellence quality",
  "technologies worked",
  "personal memorandum",
  "projects & workshops",
  "language processing",
  "interests and skill",
  "key projects",
  "tools to vmware tools",
  "personal",
  "experience",
  "personal informaion",
  "project profile 4",
  "synopsis of project",
  "certification name",
  "it skills & trainings",
  "extra curriculum",
  "professional journey",
  "personal competencies",
  "personalty traits",
  "summary of projects",
  "projects in college",
  "training / workshop",
  "projects handled",
  "overview of project",
  "carrer objective",
  "tools and frameworks",
  "languages & tools",
  "trainings undertaken",
  "total professional experience",
  "education & trainings",
  "academia & training",
  "training",
  "personal  qualities",
  "tools/apps developed",
  "language exposure",
  "last experience",
  "personality profile",
  "skill sets highlights",
  "profile statement",
  "responsibilities are",
  "internship/training",
  "it skills & training",
  "working skill",
  "hobbies & interests",
  "software proficiency",
  "summary of expertise",
  "experience sum m ary",
  "academic management",
  "achievements & honor",
  "project details ",
  "organizational experience",
  "training document",
  "training provided",
  "internship/ trainings",
  "tools/search console",
  "key skills synopsis",
  "technologies pvt ltd",
  "professional traits",
  "target job location",
  "projectsdetails",
  "professional server",
  "professional intro",
  "projects at",
  "skills highlighted",
  "training acquired",
  "tools with hands on",
  "training & awards",
  "tools profeciency",
  "career objective",
  "job profile & role",
  "skill set/strengths",
  "certifications & pdps",
  "computer details",
  "projects flawlessly",
  "training delivery",
  "personality traits",
  "academic qulification",
  "training under gone",
  "languages / skills",
  "project profile",
  "academics projects",
  "professional growth",
  "education and courses",
  "profile projector",
  "academicachievements",
  "projects delivered",
  "projects details",
  "about me",
  "personal detail",
  "declaration statement",
  "other certifications",
  "education skills",
  "profile & strengths",
  "trainings and courses",
  "certifications taken",
  "profile and reports",
  "it skills highlights",
  "technologies known",
  "experienced",
  "tools using bmc",
  "tools & software’s",
  "personal address",
  "experience",
  "professional skils",
  "work profile",
  "project summary",
  "professional experience summary",
  "training & courses",
  "experience in job",
  "personal summary",
  "training exposures",
  "internship during mms",
  "projects/achievements",
  "qualification summary",
  "placement prediction",
  "education (academic)",
  "other qualification",
  "academic qualifications",
  "languages/scripts",
  "professional (qtp)",
  "personal  statement",
  "academic record",
  "professional record",
  "education examination",
  "objectives & strength",
  "characteristic strengths",
  "employers",
  "it skills",
  "skill sets acquired",
  "profile & hobbies",
  "organization goals",
  "academia",
  "professional",
  "carrier objectives",
  "tools &technology",
  "professional condense",
  "personal exposure",
  "key achievements",
  "academics overview",
  "personal particulars",
  "telecommunication engineer",
  "database technologies & skill sets",
  "language proficiency",
  "experience & projects",
  "skills contribution",
  "language competences",
  "curriculum vintage",
  "awards & trainings",
  "training at",
  "project detailes",
  "training history",
  "achievements & awards",
  "skills &abilities",
  "overview",
  "education",
  "personal projects",
  "personal conferencing",
  "project details",
  "behavior skills",
  "engineering projects",
  "education profile",
  "experience in devops",
  "strenght",
  "projects’ details",
  "project experiences",
  "soft skills",
  "experience & exposure",
  "technical skills in",
  "skills & competencies",
  "education programme",
  "training",
  "dated",
  "rewards&achievements",
  "personalinformation",
  "hobbies and interest",
  "projects   details",
  "education summary",
  "experience at",
  "personal details",
  "project summary",
  "declairation",
  "technical skill set",
  "key skills gained",
  "mobile",
  "Mob"
  ]
  return MAINHEADERS
